version: '3.8'

services:
  catalogdb:
    image: postgres:17
    container_name: catalogdb
    environment:
      - POSTGRES_DB=CatalogDb         
      - POSTGRES_USER=postgres        
      - POSTGRES_PASSWORD=123456
    restart: always
    ports:
      - "5444:5432"
    volumes:
      - pg_data_catalog:/var/lib/postgresql/data/
    networks:
      - my_network   

volumes:
  pg_data_catalog:

networks:
  my_network: